-- Migration for adding languages
-- Assuming a table `languages` already exists with the following structure:
-- CREATE TABLE languages (code CHAR(2) PRIMARY KEY, name VARCHAR(255) NOT NULL);
INSERT INTO
  languages (code, name)
VALUES
  ('en', 'English'),
  ('fr', 'French'),
  ('es', 'Spanish'),
  ('de', 'German'),
  ('it', 'Italian'),
  ('pt', 'Portuguese'),
  ('ru', 'Russian'),
  ('zh', 'Chinese'),
  ('ja', 'Japanese'),
  ('ko', 'Korean'),
  ('ar', 'Arabic'),
  ('hi', 'Hindi'),
  ('ur', 'Urdu'),
  ('bn', 'Bengali'),
  ('sw', 'Swahili'),
  ('nl', 'Dutch'),
  ('el', 'Greek'),
  ('tr', 'Turkish'),
  ('sv', 'Swedish'),
  ('pl', 'Polish'),
  ('fi', 'Finnish'),
  ('he', 'Hebrew'),
  ('id', 'Indonesian'),
  ('ta', 'Tamil'),
  ('te', 'Telugu'),
  ('th', 'Thai'),
  ('fa', 'Persian'),
  ('gu', 'Gujarati'),
  ('kn', 'Kannada'),
  ('ml', 'Malayalam'),
  ('or', 'Odia'),
  ('pa', 'Punjabi'),
  ('mr', 'Marathi'),
  ('ne', 'Nepali'),
  ('uk', 'Ukrainian'),
  ('vi', 'Vietnamese'),
  ('ro', 'Romanian'),
  ('hu', 'Hungarian'),
  ('cs', 'Czech'),
  ('sr', 'Serbian'),
  ('hr', 'Croatian'),
  ('bg', 'Bulgarian'),
  ('da', 'Danish'),
  ('no', 'Norwegian'),
  ('sk', 'Slovak') ON CONFLICT (code) DO NOTHING;